version: '3.5'
services:
  postgres:
    build: ./docker/postgres
    image: exercicio/pgsql
    restart: on-failure
    container_name: exercicio-pgsql
    volumes:
      - ~/.exercicio-pgsql/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=default